### ISSUE TITLE
Refactor code so that also firefox can be supported

### ISSUE THREAD

**Issue by kevin0x90** [kevin0x90/dkb-online-cashback-reminder#23]
**Is your feature request related to a problem? Please describe.**
Currently the extension is only availble in chrome. To reach more users the extension should also be compatible with firefox.

**Describe the solution you'd like**
I would like to encapsulate web extension api related functionality so that the core can be independent from the underlying browser extension api calls.

**Comment by hanikesn** [comment]
I'm interested in making this happen. Do you have any pointers where to start?

**Comment by kevin0x90** [comment]
@hanikesn i would recommend to checkout the places that use methods from chrome. For example chrome.runtime... these are the methods that should be abstracted away. For reference I would recommend to checkout the web extension api Standard that is mostly inspired by the chrome api and implemented in Firefox and I guess also safari (or at least planned for one of the next versions) https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/Browser_support_for_JavaScript_APIs contains a pretty good list of the different APIs. So first step i would check what really are the differences. 

Possibly it would be already enough to only detect the browser and change the namespace from chrome to e.g. Firefox. What also would need to be researched is how compatible the manifest file properties are.

**Comment by kevin0x90** [comment]
no longer relevant
