### ISSUE TITLE
'Olympus' is recognized as 'Olymp'

### ISSUE THREAD

**Issue by electronum** [kevin0x90/dkb-online-cashback-reminder#27]
**Describe the bug**
_Olympus_ is recognized as _Olymp_

**To Reproduce**
1. Go to the website https://www.olympus.de/ or shop https://shop.olympus.eu/
2. The extension redirects to Olymp, which is a different company/shop.

**Expected behavior**
Do not show cashback notification for Olympus if not existing

**Screenshots**
![Bild 2](https://user-images.githubusercontent.com/25344206/63407429-cc5f3300-c3ec-11e9-89a8-1825dc583f5a.png)

![Bild 3](https://user-images.githubusercontent.com/25344206/63407438-ce28f680-c3ec-11e9-8b61-14c2de762255.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro
 - Chrome Version 76.0.3809.100 (64-Bit)

**Comment by kevin0x90** [comment]
Hi @electronum thanks for your bug report, i will try to fix the issue as soon as possible, maybe i have time this weekend 👍
